export const person_DATA = [ 
	{"name":"id exercitation magna occaecat","age":97,"married":false},
	{"name":"do mollit nulla","age":68,"married":false},
	{"name":"id velit reprehenderit tempor","age":99,"married":false},
	{"name":"laborum Lorem id voluptate","age":87,"married":false},
	{"name":"dolor sed","age":74,"married":true},
	{"name":"est veniam irure voluptate enim","age":52,"married":true},
	{"name":"laboris non nulla voluptate ullamco","age":50,"married":true},
	{"name":"id","age":26,"married":false},
	{"name":"Lorem amet proident eiusmod","age":67,"married":false},
	{"name":"in occaecat velit eu","age":67,"married":true},
	{"name":"Ut occaecat","age":70,"married":false},
	{"name":"ut","age":56,"married":false},
	{"name":"pariatur ex cupidatat","age":42,"married":true},
	{"name":"dolore ad fugiat ut","age":36,"married":false},
	{"name":"nisi ut","age":77,"married":false},
	{"name":"mollit labore Ut exercitation Duis","age":15,"married":true},
	{"name":"in minim Lorem velit ipsum","age":15,"married":true},
	{"name":"dolor labore","age":12,"married":true},
	{"name":"in et ad","age":63,"married":true},
	{"name":"irure ut","age":14,"married":false},
]